/**
 * GhostNote Universal Language Engine
 * 10 Core Languages with UI Translations
 */

export const LANGUAGES = [
    { code: 'EN', name: 'English', native: 'English' },
    { code: 'FR', name: 'French', native: 'Français' },
    { code: 'ES', name: 'Spanish', native: 'Español' },
    { code: 'ZH', name: 'Chinese', native: '中文' },
    { code: 'RU', name: 'Russian', native: 'Русский' },
    { code: 'DE', name: 'German', native: 'Deutsch' },
    { code: 'JA', name: 'Japanese', native: '日本語' },
    { code: 'PT', name: 'Portuguese', native: 'Português' },
    { code: 'AR', name: 'Arabic', native: 'العربية' },
    { code: 'HI', name: 'Hindi', native: 'हिन्दी' },
];

export const TRANSLATIONS = {
    EN: {
        prompt: 'Tap to begin',
        record: 'Record',
        upload: 'Upload',
        btn_transmute: 'TRANSMUTE AUDIO',
        btn_copy: 'COPY',
        btn_mint: 'MINT ARTIFACT',
        btn_regenerate: 'REGENERATE',
        select_file: 'Select audio file',
        processing: 'TRANSMUTING...',
        gift: 'Gift Ghostnote Pro',
    },
    FR: {
        prompt: 'Touchez pour commencer',
        record: 'Enregistrer',
        upload: 'Télécharger',
        btn_transmute: 'TRANSMUTER L\'AUDIO',
        btn_copy: 'COPIER',
        btn_mint: 'CRÉER ARTEFACT',
        btn_regenerate: 'RÉGÉNÉRER',
        select_file: 'Sélectionner un fichier audio',
        processing: 'TRANSMUTATION...',
        gift: 'Offrir Ghostnote Pro',
    },
    ES: {
        prompt: 'Toca para comenzar',
        record: 'Grabar',
        upload: 'Subir',
        btn_transmute: 'TRANSMUTAR AUDIO',
        btn_copy: 'COPIER',
        btn_mint: 'CREAR ARTEFACTO',
        btn_regenerate: 'REGENERAR',
        select_file: 'Seleccionar archivo de audio',
        processing: 'TRANSMUTANDO...',
        gift: 'Regalar Ghostnote Pro',
    },
    ZH: {
        prompt: '点击开始',
        record: '录制',
        upload: '上传',
        btn_transmute: '转化音频',
        btn_copy: '复制',
        btn_mint: '铸造',
        btn_regenerate: '重新生成',
        select_file: '选择音频文件',
        processing: '转化中...',
        gift: '分享 Ghostnote Pro',
    },
    RU: {
        prompt: 'Нажмите, чтобы начать',
        record: 'Запись',
        upload: 'Загрузить',
        btn_transmute: 'ТРАНСМУТИРОВАТЬ',
        btn_copy: 'КОПИРОВАТЬ',
        btn_mint: 'СОЗДАТЬ АРТЕФАКТ',
        btn_regenerate: 'ПОВТОРИТЬ',
        select_file: 'Выберите аудио файл',
        processing: 'ОБРАБОТКА...',
        gift: 'Подарить Ghostnote Pro',
    },
    DE: {
        prompt: 'Zum Starten tippen',
        record: 'Aufnehmen',
        upload: 'Hochladen',
        btn_transmute: 'AUDIO TRANSMUTIEREN',
        btn_copy: 'KOPIEREN',
        btn_mint: 'ARTEFAKT ERSTELLEN',
        btn_regenerate: 'REGENERIEREN',
        select_file: 'Audiodatei auswählen',
        processing: 'TRANSMUTIERE...',
        gift: 'Ghostnote Pro verschenken',
    },
    JA: {
        prompt: 'タップして開始',
        record: '録音',
        upload: 'アップロード',
        btn_transmute: 'オーディオを変換',
        btn_copy: 'コピー',
        btn_mint: 'アーティファクト作成',
        btn_regenerate: '再生成',
        select_file: 'オーディオファイルを選択',
        processing: '変換中...',
        gift: 'Ghostnote Proを共有',
    },
    PT: {
        prompt: 'Toque para começar',
        record: 'Gravar',
        upload: 'Carregar',
        btn_transmute: 'TRANSMUTAR ÁUDIO',
        btn_copy: 'COPIAR',
        btn_mint: 'CRIAR ARTEFATO',
        btn_regenerate: 'REGENERAR',
        select_file: 'Selecionar arquivo de áudio',
        processing: 'TRANSMUTANDO...',
        gift: 'Presentear Ghostnote Pro',
    },
    AR: {
        prompt: 'انقر للبدء',
        record: 'تسجيل',
        upload: 'رفع',
        btn_transmute: 'تحويل الصوت',
        btn_copy: 'نسخ',
        btn_mint: 'إنشاء أثر',
        btn_regenerate: 'إعادة التوليد',
        select_file: 'اختر ملف صوتي',
        processing: 'جارٍ التحويل...',
        gift: 'مشاركة Ghostnote Pro',
    },
    HI: {
        prompt: 'शुरू करने के लिए टैप करें',
        record: 'रिकॉर्ड',
        upload: 'अपलोड',
        btn_transmute: 'ऑडियो ट्रांसम्यूट करें',
        btn_copy: 'कॉपी',
        btn_mint: 'आर्टिफैक्ट बनाएं',
        btn_regenerate: 'पुनः उत्पन्न करें',
        select_file: 'ऑडियो फ़ाइल चुनें',
        processing: 'प्रसंस्करण...',
        gift: 'Ghostnote Pro साझा करें',
    },
};

export const getLanguageName = (code) => {
    const lang = LANGUAGES.find(l => l.code === code);
    return lang ? lang.name : 'English';
};
